apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: customer-api
spec:
  generators:
  - list:
      elements:
      - namespace: dev
        url: https://kubernetes.default.svc
      - namespace: stage
        url: https://kubernetes.default.svc
      - namespace: prod
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{namespace}}-customer-api'
    spec:
      project: default
      source:
        repoURL: https://github.com/onurkanbakirci/tesodev.case.git
        targetRevision: HEAD
        path: deploy/k8s/helm/customer-api-chart
        helm:
          releaseName: customer-api
          valueFiles:
            - environments/{{namespace}}/values.yaml
            - environments/{{namespace}}/version.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:  {}