name: "Deploy docker image"
description: "Deploy docker image to github registry"

inputs:
  context:
    description: "Context path for docker process"
    required: true
  file:
    description: "Docker file location"
    required: true
  tags:
    description: "Image registry tag e.g. myacr.azureacr.io/eshop"
    required: true
  push:
    description: "Whether push image to registry or not"
    required: false
    default: "true"
  token:
    description: "Security token"
    required: true
  actor:
    description: "Actor of docker build"
    required: true

runs:
  using: "composite"
  steps:

    - name: Login to Github Packages
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ inputs.actor }}
        password: ${{ inputs.token }}

    - name: Build ${{ inputs.tags }} image and push to registry
      uses: docker/build-push-action@v2
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.file }}
        tags: ${{ inputs.tags }}
        push: ${{ inputs.push }}
