name: "Deploy cluster"
description: "Deploy charts to cluster"

inputs:
  chart:
    description: "Name of to chart which will be deployed to cluster"
    required: true
  registry:
    description: "Name of the helm charts registry"
    required: true
  kube_config_secret:
    description: "Kubeconfig secret of cluster"
    required: true
  repo_secret:
    description: "Repo secret"
    required: true
  repo_name:
    description: "Kubeconfig secret of cluster"
    required: true
  repo_url:
    description: "Repo secret"
    required: true

runs:
  using: "composite"
  steps:
    - name: deploy postgres to cluster
      uses: wahyd4/kubectl-helm-action@master
      env:
        KUBE_CONFIG_DATA: ${{inputs.kube_config_secret}}
      with:
        args: |
          helm repo add --username ${{inputs.actor}} --password ${{inputs.repo_secret}} ${{inputs.repo_name}} ${{inputs.repo_url}}
          helm repo update
          helm upgrade --install ${{inputs.chart}} ${{inputs.repo_name}}/${{inputs.chart}}