name: Customer Api

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - main

    paths:
      - src/Services/Customer/**
      - deploy/k8s/helm/customer-api-chart/**
      - .github/workflows/customer-api.yml
      - .github/workflows/composite/**

env:
  dotnet_version: 8.x

  #For test process
  test_project_path: tests/Tesodev.Case.Customer.UnitTests/

  #For docker build process
  owner: onurkanbakirci
  repo: tesodev.case
  context: .
  docker_file_path: src/Services/Customer/Tesodev.Case.Customer.API/Dockerfile
  push: true
  docker_image_tag: ghcr.io/onurkanbakirci/tesodev.case/customer-api:1.0.0

jobs:
  test:
    name: Test Api
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.dotnet_version }}

      - name: Run Tests
        run: |
          cd ${{env.test_project_path}}
          dotnet restore
          dotnet build --configuration Release --no-restore
          dotnet test --no-restore --verbosity normal

  build-docker-image:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: test
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: ./.github/workflows/composite/deploy-docker
        with:
          context: ${{ env.context }}
          tags: ${{env.docker_image_tag}}
          file: ${{ env.docker_file_path }}
          push: ${{ env.push }}
          actor: ${{github.actor}}
          token: ${{secrets.GITHUB_TOKEN}}

  deploy-to-heroku:
    name: Deploy Docker Image
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: ./.github/workflows/composite/deploy-heroku
        with:
          token: ${{ secrets.HEROKU_API_KEY }}
          app_name: "tesodev-case"
          mail: "onurkanbkrc@gmail.com"