name: Web Api Gateway

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - main

    paths:
      - src/ApiGateways/WebApiGateway/Tesodev.Case.WebApiGateway/**
      - deploy/k8s/helm/web-api-gateway-chart/**
      - .github/workflows/web-api-gateway.yml
      - .github/workflows/composite/**

env:
  #For docker build process
  owner: onurkanbakirci
  repo: tesodev.case
  context: .
  docker_file_path: src/ApiGateways/WebApiGateway/Tesodev.Case.WebApiGateway/Tesodev.Case.WebApiGateway/Dockerfile
  push: true
  docker_image_tag: ghcr.io/onurkanbakirci/tesodev.case/web-api-gateway:1.0.0

jobs:
  test:
    name: Test Api
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.dotnet_version }}

      - name: Run Tests
        run: |
          cd ${{env.test_project_path}}
          dotnet restore
          dotnet build --configuration Release --no-restore
          dotnet test --no-restore --verbosity normal

  build-docker-image:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: test
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: ./.github/workflows/composite/deploy-docker
        with:
          context: ${{ env.context }}
          tags: ${{env.docker_image_tag}}
          file: ${{ env.docker_file_path }}
          push: ${{ env.push }}
          actor: ${{github.actor}}
          token: ${{secrets.GITHUB_TOKEN}}
